# Generated by Django 3.2.5 on 2021-07-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('litros', models.FloatField()),
                ('link', models.URLField()),
            ],
            options={
                'unique_together': {('nome', 'litros')},
            },
        ),
    ]
