# Generated by Django 3.2.5 on 2021-07-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_suco_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suco',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
