# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import produto_pb2 as produto__pb2


class Produto_EntregueStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EntregaProduto = channel.unary_unary(
                '/Produto_Entregue/EntregaProduto',
                request_serializer=produto__pb2.Produto.SerializeToString,
                response_deserializer=produto__pb2.Resposta.FromString,
                )


class Produto_EntregueServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EntregaProduto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Produto_EntregueServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EntregaProduto': grpc.unary_unary_rpc_method_handler(
                    servicer.EntregaProduto,
                    request_deserializer=produto__pb2.Produto.FromString,
                    response_serializer=produto__pb2.Resposta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Produto_Entregue', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Produto_Entregue(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EntregaProduto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Produto_Entregue/EntregaProduto',
            produto__pb2.Produto.SerializeToString,
            produto__pb2.Resposta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
