# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: produto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='produto.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rproduto.proto\"@\n\x07Produto\x12\x0f\n\x07produto\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x61ta_entrega\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\"\x1c\n\x08Resposta\x12\x10\n\x08resposta\x18\x01 \x01(\t2;\n\x10Produto_Entregue\x12\'\n\x0e\x45ntregaProduto\x12\x08.Produto\x1a\t.Resposta\"\x00\x62\x06proto3'
)




_PRODUTO = _descriptor.Descriptor(
  name='Produto',
  full_name='Produto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='produto', full_name='Produto.produto', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_entrega', full_name='Produto.data_entrega', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='Produto.status', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=81,
)


_RESPOSTA = _descriptor.Descriptor(
  name='Resposta',
  full_name='Resposta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resposta', full_name='Resposta.resposta', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['Produto'] = _PRODUTO
DESCRIPTOR.message_types_by_name['Resposta'] = _RESPOSTA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Produto = _reflection.GeneratedProtocolMessageType('Produto', (_message.Message,), {
  'DESCRIPTOR' : _PRODUTO,
  '__module__' : 'produto_pb2'
  # @@protoc_insertion_point(class_scope:Produto)
  })
_sym_db.RegisterMessage(Produto)

Resposta = _reflection.GeneratedProtocolMessageType('Resposta', (_message.Message,), {
  'DESCRIPTOR' : _RESPOSTA,
  '__module__' : 'produto_pb2'
  # @@protoc_insertion_point(class_scope:Resposta)
  })
_sym_db.RegisterMessage(Resposta)



_PRODUTO_ENTREGUE = _descriptor.ServiceDescriptor(
  name='Produto_Entregue',
  full_name='Produto_Entregue',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=113,
  serialized_end=172,
  methods=[
  _descriptor.MethodDescriptor(
    name='EntregaProduto',
    full_name='Produto_Entregue.EntregaProduto',
    index=0,
    containing_service=None,
    input_type=_PRODUTO,
    output_type=_RESPOSTA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRODUTO_ENTREGUE)

DESCRIPTOR.services_by_name['Produto_Entregue'] = _PRODUTO_ENTREGUE

# @@protoc_insertion_point(module_scope)
